name: Sync services
on:
  repository_dispatch:
      # this workflow is triggered by an external script that calls the GitHub API
      # when a new version of the JS API client is released. Without this filter,
      # the workflow would run on every incoming dispatch event, not just this one.
    types:
      - latest-api-js-client-version

jobs:
  sync-js-client-version:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Prod Env  
        uses: actions/checkout@v3 
        with:
          token: ${{ secrets.INNER_CIRCLE_TIME_UI_TRIGGER_TOKEN }}

      - name: Set branch name
        run: 
          echo "BRANCH_NAME=feature/sync-js-client-version-to-${{ github.event.client_payload.client-version }}-$(date +'%FT%H-%M')" >> $GITHUB_ENV

      # double quotes and new lines in multiline commit message breaks the sync workflow
      # using json to file trick that replaces double quotes and new lines with \" and \n
      # -e is used to enable interpretation of the following backslash escapes (e.g \n)
      - name: Write commit message to file
        run: 
          echo -e ${{ toJson(github.event.client_payload.commit_message) }} > commit_message.txt

      - name: Write new api js-client version to package.json
        run: |
          sed -i "0,/\"@tourmalinecore\/inner-circle-time-api-js-client\": .*/s//\"@tourmalinecore\/inner-circle-time-api-js-client\": \"^${{ github.event.client_payload.client-version }}\",/" package.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name github-actions[bot]
          # 41898282 is id of GitHub Actions Bot that was taken from GitHub API: https://api.github.com/users/github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

          git checkout -b $BRANCH_NAME master

          git add package.json

          git commit -F commit_message.txt
          
          git push origin $BRANCH_NAME

      - name: Set PR title
        run: 'echo "PR_TITLE=infra: update js-client to ${{ github.event.client_payload.client-version }}" >> $GITHUB_ENV' 
        
      - name: Create PR
        run: gh pr create -B master -H $BRANCH_NAME --title "${{ env.PR_TITLE }}" -F commit_message.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve PR
        run: gh pr review $BRANCH_NAME -a
        env:
          GITHUB_TOKEN: ${{ secrets.INNER_CIRCLE_TIME_UI_TRIGGER_TOKEN }}

      - name: Enable auto-merge for PR
        run: gh pr merge $BRANCH_NAME --auto --merge --subject "${{ env.PR_TITLE }}" -F commit_message.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
